/* Orbit · scripts/fonts.mjs
   `npm run fonts` — cuts assets/fonts.source.css down to assets/fonts.css.

   The source stylesheet holds the Fell faces as their publishers shipped them, with every character
   they were drawn for. The atlas sets a few hundred of those and carries the rest across the wire for
   nothing, so this writes a second stylesheet containing the same faces with only the characters the
   game can actually produce, and it is that one the page loads. The source is kept beside it and is
   never shipped: a subset cannot be widened back out, so the full faces have to stay somewhere.

   Run it after changing the embedded faces or after adding a character the game sets — and then run
   `npm run glyphs`, which reads the source stylesheet rather than this output for the same reason.  */
import {readFile,readdir,writeFile} from 'node:fs/promises';
import subsetFont from 'subset-font';

const root=new URL('../',import.meta.url);
const SOURCE='assets/fonts.source.css',OUT='assets/fonts.css';

// What the atlas can set, read off the atlas itself rather than kept as a list here that would drift
// out of step with it. Every character in the source counts — every string literal reaches the screen
// one way or another, and the code around them is ASCII, which the game sets anyway for scores and
// initials. Printable ASCII is added whole so a character that only ever appears at runtime is still
// cut in. Add a caption with a character the faces have not been cut for and it will fall back to
// Georgia until this is run again; that is the same staleness `npm run glyphs` already has.
const SCANNED=['src/index.html',...(await readdir(new URL('src/',root))).filter(n=>n.endsWith('.js')).map(n=>'src/'+n)];
const charset=await (async()=>{
  const seen=new Set();
  for(let c=0x20;c<=0x7e;c++)seen.add(String.fromCharCode(c));
  for(const file of SCANNED)for(const ch of await readFile(new URL(file,root),'utf8'))if(ch>' ')seen.add(ch);
  return [...seen].sort().join('');
})();

const css=await readFile(new URL(SOURCE,root),'utf8');
// Each face is one @font-face block carrying one base64 woff2; rebuild the block around the subset.
const FACE=/@font-face\{([^}]*?)src:url\(data:font\/woff2;base64,([A-Za-z0-9+/=]+)\)([^}]*)\}/g;
let out=css,cut=0,kept=0,faces=0;
const jobs=[];
for(const match of css.matchAll(FACE))jobs.push(match);
if(!jobs.length)throw new Error(SOURCE+' holds no base64 woff2 face.');
for(const [block,head,base64,tail] of jobs){
  const before=Buffer.from(base64,'base64');
  const after=await subsetFont(before,charset,{targetFormat:'woff2'});
  const family=/font-family:'([^']+)'/.exec(head)?.[1]??'?';
  const style=/font-style:(\w+)/.exec(head)?.[1]??'normal';
  console.log(`  ${family} ${style}: ${(before.length/1024).toFixed(0)} KB -> ${(after.length/1024).toFixed(0)} KB`);
  cut+=before.length;kept+=after.length;faces++;
  out=out.replace(block,`@font-face{${head}src:url(data:font/woff2;base64,${after.toString('base64')})${tail}}`);
}
const note=`/* Generated by scripts/fonts.mjs from ${SOURCE} — do not edit by hand.\n`+
  `   The same faces, cut to the ${charset.length} characters the atlas can set. */\n`;
await writeFile(new URL(OUT,root),note+out.replace(/^\/\*[\s\S]*?\*\/\n/,''));
console.log(`${OUT} written: ${faces} faces, ${(cut/1024).toFixed(0)} KB of woff2 cut to ${(kept/1024).toFixed(0)} KB `+
  `(${(100-kept/cut*100).toFixed(0)}% smaller), at ${charset.length} characters.`);
